### ISSUE TITLE
Formatting (often) results in garbled, uncompilable code 

### ISSUE THREAD

**Issue by kodfodrasz** [deviousasti/fsharp-formatting-for-vs#14] opened 2021-02-23 18:52 UTC
Formatting an F# file garbles the file, and results in uncompilable code. 

Strange artifacts get introduced tot he code. Running fantomas from the command line does not cause this.

I can reproduce for example with this example:

### input
~~~fsharp
module Repro

open System.Text.RegularExpressions

type Capacity = Capacity of count: int * item: string
type Container = Container of container: string * capacity: Capacity list

let parseInputLine (line: string) =
  let m =
    Regex.Match
      (line,
       """(?<container>\w+ \w+) bags contain (?<contents>no other bags|((?<count>\d+) (?<item>\w+ \w+) bag(s)?(, )?)+).""")
  ()
~~~

now I press `Ctrl-E Ctrl-D`

### output
~~~fsharp
module Repro

open System.Text.RegularExpressions

type Capacity = Capacity of count: int * item: string
type Container = Container of container: string * capacity: Capacity list
    Regex.Match(
      line,
      """(?<container>\w+ \w+) bags contain (?<contents>no other bags|((?<count>\d+) (?<item>\w+ \w+) bag(s)?(, )?)+)."""
    )

  ()
      (line,
       """(?<container>\w+ \w+) bags contain (?<contents>no other bags|((?<count>\d+) (?<item>\w+ \w+) bag(s)?(, )?)+).""")
  ()
~~~

#### Visual Studio
~~~
Microsoft Visual Studio Community 2019
Version 16.8.6
VisualStudio.16.Release/16.8.6+31019.35
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA182
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.560.26713
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.560.26713
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.560.26713
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.560.26713
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

F# Formatting   0.8
F# source code formatting using Fantomas.

F# Lint   0.5
Source code linting for F#.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes
~~~

#### Fantomas

I also have `Fantomas v4.3.0-alpha-005` installed, which does the formatting without issues. (this preview version contains the eol enforcing I need on some projects, probably should update)

#### Editorconfig 

I use editorconfig, but after having deleted it and restarted VS the problem still persisted. Nonetheless I attach it.
~~~
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 2
~~~

Please let me know how can I help tracing down the problem.

Thank you very much!

**Comment by deviousasti** [comment] 2021-02-24 01:00
Hi Gábor,

First off, thank you for providing such a detailed report. 
We can rule out a number of cases just based on that.

I'm not able to reproduce the problem, unfortunately.
I'm on VS 16.9 Preview 4.

Could you try toggling the formatter version - if it's Latest, it's on `4.4.0 beta 8` and Stable it's on `4.3.0 `.
![image](https://user-images.githubusercontent.com/2375486/108926479-88de2880-7664-11eb-8131-5fb989e38afa.png)

**Comment by kodfodrasz** [comment] 2021-02-25 09:24
Hi!

I have ran `sfc /scannow`, and Repair on the Visual Studio installation from the Visual Studio Installer, just in case. Reinstalled the extension afterwards.

I have tried both Stable and Latest versions. Both exhibit the same erroneous behavior.

I have updated fantomas to latest stable version (4.4.0), and it still does not exhibit problematic behavior, it formats the files as expected.

**Comment by kodfodrasz** [comment] 2021-02-25 09:31
After having poked around the options the "Apply As Diff" option seems to be the problematic part. When disabling it the formatter works as expected. (albeit whole file is marked as changed).

I'm using UNIX file endings in many projects. Maybe that can be the cause of some offset problems when calculating the diff?

**Comment by deviousasti** [comment] 2021-02-25 09:32
Yikes, that sounds pretty off.

Could you try downloading this and try formatting it?
https://www.dropbox.com/s/59iapleqviuo8r8/Program.fsx?dl=1
This is CRLF and UTF-8 BOM.

Another thing you can do is try to set `Apply As Diff` to False.

**Comment by deviousasti** [comment] 2021-02-25 09:42
Ah, so that's definitely the suspect. It should really be line-ending agnostic - I'm currently using the Diffplex library. 
Issue #13 is also related to the diffing library. Maybe it's time to try some alternatives.

I'll try to work on a fix soon, so in the mean time could you please adjust with the diff turned off?

**Comment by kodfodrasz** [comment] 2021-02-25 09:49
For now I have set `Apply As Diff` to false, as the tool working from the IDE instead of running fantomas manually from the cli is worth way more for me than the correctly colored margins on VS editor. 🙂

When reenabling the `Apply As Diff` the example file is properly formatted. 

The following file (the original I extracted the repro example, but in verbatim binary copy) is still incorrectly formatted:

http://files.kodfodrasz.net/Day7.fs

This is `UTF-8 NO-BOM, LF` line endings.

**Comment by deviousasti** [comment] 2021-02-25 10:14
I can see where it breaks - that's a good repro. 

P.S.
If you're trying advent of code, I'd like to recommend F# Worksheet.
https://github.com/deviousasti/fsharp-worksheet

It makes exploratory coding fairly fun.

**Comment by davidspiess** [comment] 2021-02-26 08:37
Same problem as @kodfodrasz. `Apply As Diff` fixed it for me too!

**Comment by deviousasti** [comment] 2021-02-26 08:47
@davidspiess The same Unix line-endings as well?

**Comment by davidspiess** [comment] 2021-02-26 08:48
@deviousasti yes, this is my editorconfig:
```
[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

**Comment by deviousasti** [comment] 2021-03-23 21:12
Dear @davidspiess and @kodfodrasz 

I've shipped a better diff model which is line-ending agnostic, and also results in smaller diffs.
Could you please update (to 0.8.3) and let me know how it works now (with `Apply As Diff` turned on)?

**Comment by davidspiess** [comment] 2021-03-23 21:23
@deviousasti it formats correctly, thank you!

**Comment by deviousasti** [comment] 2021-03-23 21:36
Just pushed 0.8.4 which shrinks the diff before applying to the edit buffer, hopefully fixing #13.
Thanks for the report!

**Comment by kodfodrasz** [comment] 2021-03-23 22:46
I have just tired it. The previously problematic file was formatted perfectly. Will test it further in the next days, but for the glimpse it seems like the problem is solved!

Thank you very much!

**Comment by deviousasti** [comment] 2021-03-24 04:12
The fix was a bit more complicated than I expected. 🙂

Feel free to close this after you've tested it!

**Closed** 2021-03-26 11:04 UTC
